<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Theme\Block\Html\Footer;
use Magento\Framework\Escaper;

/** @var Footer $block */
/** @var Escaper $escaper */
?>
<div class="grow flex justify-between items-center gap-4 sm:ml-6 sm:mt-0 mt-4">
    <small class="text-sm text-gray-800">
        <?= $escaper->escapeHtml($block->getCopyright()) ?>
    </small>
    <div class="text-sm">
        <?= $block->getChildHtml() ?>
    </div>
</div>
