<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoMenus\ViewModel\StoreInfoMenus;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfoMenus $storeMenu */
$storeMenus = $block->getData('viewModelStoreInfo');

$menu = $storeMenus->getAboutMenu();

if (count($menu) === 0) {
    return '';
}

?>

<ul class="footer links">
    <?php foreach ($menu as $item): ?>
        <li class="nav item">
            <a href="<?= $escaper->escapeUrl($block->getUrl($item['url'])); ?>">
                <?= $escaper->escapeHtml($item['text']); ?>
            </a>
        </li>
    <?php endforeach ?>
</ul>
