<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoMenus\ViewModel\StoreInfoMenus;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfoMenus $storeMenu */
$storeMenus = $viewModels->require(StoreInfoMenus::class);

$menu = $storeMenus->getLegalMenu();

if (count($menu) === 0) {
    return '';
}

?>

<div class="pr-4 lg:w-1/4 md:w-1/2">
    <h2 class="text-md leading-5 font-semibold tracking-wider uppercase">
        <?= $escaper->escapeHtml(__('Legal')) ?>
    </h2>
    <ul class="mt-4 space-y-4">
        <?php foreach ($menu as $item): ?>
            <li>
                <a
                    href="<?= $escaper->escapeUrl($block->getUrl($item['url'])); ?>"
                    class="hover:underline"
                ><?= $escaper->escapeHtml($item['text']); ?></a>
            </li>
        <?php endforeach ?>
    </ul>
</div>
