<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2023 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoMenus\ViewModel\StoreInfoMenus;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfoMenus $storeMenu */
$storeMenus = $viewModels->require(StoreInfoMenus::class);

$menu = $storeMenus->getServicesMenu();

$title = $block->getTitle() ?: "Services";
$showTitle = $block->getShowTitle() !== null ? $block->getShowTitle() : true;

$classList = $block->getClassList() !== null ? $block->getClassList() : 'pr-4 lg:w-1/4 md:w-1/2';
$classListTitle = $block->getClassListTitle() !== null ? $block->getClassListTitle() : 'text-md leading-5 font-semibold tracking-wider uppercase';
$classListMenu = $block->getClassListMenu() !== null ? $block->getClassListMenu() : 'mt-4 space-y-4';
$classListMenuItem = $block->getClassListMenuItem() !== null ? $block->getClassListMenuItem() : 'font-medium hover:underline';

if (count($menu) === 0) {
    return '';
}

?>

<nav
    class="<?= $escaper->escapeHtmlAttr($classList) ?>"
    aria-label="<?= $escaper->escapeHtml(__('%1 Menu', $title)) ?>"
>
    <?php if ($showTitle): ?>
        <h2 class="<?= $escaper->escapeHtmlAttr($classListTitle) ?>">
            <?= $escaper->escapeHtml($title) ?>
        </h2>
    <?php endif; ?>
    <ul class="<?= $escaper->escapeHtmlAttr($classListMenu) ?>">
        <?php foreach ($menu as $item): ?>
            <li>
                <a
                    href="<?= $escaper->escapeUrl($block->getUrl($item['url'])); ?>"
                    class="<?= $escaper->escapeHtmlAttr($classListMenuItem) ?>"
                ><?= $escaper->escapeHtml($item['text']); ?></a>
            </li>
        <?php endforeach ?>
    </ul>
</nav>

