<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2023 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoMenus\ViewModel\StoreInfoMenus;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfoMenus $storeMenu */
$storeMenus = $block->getStoreInfoMenus();

$classes = $block->getCssClasses() ?? 'footer links';

$headingTag = $block->getHeadingTag() ?? 'h2';
$headingText = $block->getTitle() ?: "";
$showHeading = $block->getShowHeading() !== null ? $block->getShowHeading() : true;
$headingClasses = $block->getHeadingCssClasses() ?? 'title mb-4 text-md leading-5 font-semibold tracking-wider uppercase';

$menuId = $block->getData('menu_id') ?: '';
$menuHeading = $storeMenus->getMenuHeading($menuId) ?: $headingText;
$menuItems = $storeMenus->getMenu($menuId);
$menuClasses = $block->getMenuCssClasses() !== null ? $block->getMenuCssClasses() : 'space-y-4 font-medium';

if (count($menuItems) === 0) {
    return '';
}

?>

<nav
    class="<?= $escaper->escapeHtmlAttr($classes) ?>"
    aria-label="<?= $escaper->escapeHtml(__('%1 Menu', $menuHeading)) ?>"
>
    <?php if ($showHeading && $menuHeading): ?>
        <<?= $escaper->escapeHtmlAttr($headingTag) ?>
            class="<?= $escaper->escapeHtmlAttr($headingClasses) ?>"
        >
            <?= $escaper->escapeHtml($menuHeading) ?>
        </<?= $escaper->escapeHtmlAttr($headingTag) ?>>
    <?php endif; ?>
    <ul class="<?= $escaper->escapeHtmlAttr($menuClasses) ?>">
        <?php foreach ($menuItems as $item): ?>
            <li class="nav item">
                <a href="<?= $escaper->escapeUrl($storeMenus->getUrl($item['url'])); ?>" class="hover:underline">
                    <?= $escaper->escapeHtml($item['text']); ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
</nav>
